# Generated by Django 5.2.17 on 2026-08-15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("processing", "0004_sourcedocument_retention_deadline_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OcrRun",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("engine", models.CharField(max_length=32)),
                ("engine_version", models.CharField(max_length=128)),
                ("model_versions", models.JSONField(default=dict)),
                ("languages", models.JSONField(default=list)),
                ("configuration_encrypted", models.TextField()),
                ("preprocessing_encrypted", models.TextField(blank=True)),
                ("selected_preprocessing_variant", models.CharField(blank=True, max_length=32)),
                ("raw_output_encrypted", models.TextField(blank=True)),
                ("succeeded", models.BooleanField(default=False)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("source_document", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ocr_runs", to="processing.sourcedocument")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ocr_runs", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ("created_at",),
                "indexes": [models.Index(fields=["user", "source_document", "created_at"], name="ocr_run_document_idx")],
            },
        ),
    ]
