# Generated by Django 5.2.17 on 2026-08-15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ocr", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="ocrrun",
            name="model_versions",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="OcrToken",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("text_encrypted", models.TextField()),
                ("confidence", models.FloatField()),
                ("left", models.PositiveIntegerField()),
                ("top", models.PositiveIntegerField()),
                ("right", models.PositiveIntegerField()),
                ("bottom", models.PositiveIntegerField()),
                ("page_number", models.PositiveIntegerField(default=0)),
                ("block_number", models.PositiveIntegerField(default=0)),
                ("paragraph_number", models.PositiveIntegerField(default=0)),
                ("line_number", models.PositiveIntegerField(default=0)),
                ("word_number", models.PositiveIntegerField(default=0)),
                ("sequence", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ocr_run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tokens", to="ocr.ocrrun")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ocr_tokens", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ("sequence",),
                "indexes": [
                    models.Index(fields=["ocr_run", "sequence"], name="ocr_token_reading_idx"),
                    models.Index(fields=["ocr_run", "top", "left"], name="ocr_token_spatial_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("ocr_run", "sequence"), name="ocr_token_run_sequence_unique"),
                    models.CheckConstraint(condition=models.Q(("confidence__gte", 0.0), ("confidence__lte", 1.0)), name="ocr_token_confidence_range"),
                    models.CheckConstraint(condition=models.Q(("right__gte", models.F("left"))), name="ocr_token_horizontal_bounds"),
                    models.CheckConstraint(condition=models.Q(("bottom__gte", models.F("top"))), name="ocr_token_vertical_bounds"),
                ],
            },
        ),
    ]
