# Generated by Django 5.2.17 on 2026-08-15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("ocr", "0002_ocrtoken")]

    operations = [
        migrations.AddField(
            model_name="ocrtoken",
            name="normalized_text_encrypted",
            field=models.TextField(default=""),
            preserve_default=False,
        )
    ]
