# Generated by Django 5.2.17 on 2026-08-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0003_ocrtoken_normalized_text_encrypted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrrun',
            name='engine',
            field=models.CharField(choices=[('paddleocr', 'PaddleOCR'), ('tesseract', 'Tesseract')], max_length=32),
        ),
    ]
