# Generated by Django 5.2.17 on 2026-08-07 06:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_encrypted', models.TextField()),
                ('name_blind_index', models.CharField(max_length=128)),
                ('institution_encrypted', models.TextField()),
                ('institution_blind_index', models.CharField(max_length=128)),
                ('account_type', models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('cash', 'Cash'), ('credit_card_liability', 'Credit-card liability'), ('loan', 'Loan'), ('investment', 'Investment'), ('other_asset', 'Other asset'), ('other_liability', 'Other liability')], max_length=32)),
                ('masked_identifier_encrypted', models.TextField(blank=True)),
                ('identifier_last_four', models.CharField(blank=True, max_length=4)),
                ('currency', models.CharField(default='KRW', max_length=3)),
                ('opening_balance_encrypted', models.TextField(default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name_blind_index', 'created_at'),
                'indexes': [models.Index(fields=['user', 'is_active'], name='financial_account_active_idx'), models.Index(fields=['user', 'account_type'], name='financial_account_type_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'name_blind_index'), name='financial_account_user_name_blind_unique')],
            },
        ),
    ]
