# Generated by Django 5.2.17 on 2026-08-14 07:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='financialaccount',
            constraint=models.CheckConstraint(condition=models.Q(('account_type__in', ('checking', 'savings', 'cash', 'credit_card_liability', 'loan', 'investment', 'other_asset', 'other_liability'))), name='financial_account_type_valid'),
        ),
    ]
