# Generated by Django 5.2.17 on 2026-08-19 11:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_accounts', '0002_financialaccount_financial_account_type_valid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaccount',
            name='identifier_blind_index',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddIndex(
            model_name='financialaccount',
            index=models.Index(fields=['user', 'institution_blind_index'], name='financial_account_inst_idx'),
        ),
        migrations.AddIndex(
            model_name='financialaccount',
            index=models.Index(fields=['user', 'identifier_blind_index'], name='financial_account_ident_idx'),
        ),
    ]
