# Generated by Django 5.2.17 on 2026-08-07 06:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financial_accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInstrument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_encrypted', models.TextField()),
                ('name_blind_index', models.CharField(max_length=128)),
                ('instrument_type', models.CharField(choices=[('debit_card', 'Debit card'), ('credit_card', 'Credit card'), ('virtual_card', 'Virtual card'), ('prepaid_card', 'Prepaid card'), ('other', 'Other')], max_length=24)),
                ('last_four', models.CharField(blank=True, max_length=4)),
                ('issuer_encrypted', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financial_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_instruments', to='financial_accounts.financialaccount')),
                ('settlement_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlement_instruments', to='financial_accounts.financialaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_instruments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name_blind_index', 'created_at'),
                'indexes': [models.Index(fields=['user', 'is_active'], name='instrument_user_active_idx'), models.Index(fields=['user', 'instrument_type'], name='instrument_user_type_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'name_blind_index'), name='instrument_user_name_blind_unique')],
            },
        ),
    ]
