# Generated by Django 5.2.17 on 2026-08-09 11:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('object_type', models.CharField(blank=True, max_length=128)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('ip_hash', models.CharField(blank=True, max_length=128)),
                ('user_agent_hash', models.CharField(blank=True, max_length=128)),
                ('metadata', models.JSONField(default=dict)),
                ('previous_digest', models.CharField(blank=True, max_length=128)),
                ('digest', models.CharField(editable=False, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at', 'id'),
                'indexes': [models.Index(fields=['user', 'created_at'], name='audit_user_created_idx'), models.Index(fields=['user', 'event_type'], name='audit_user_event_idx')],
            },
        ),
    ]
