# Generated by Django 5.2.17 on 2026-08-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Login succeeded'), ('login_failure', 'Login failed'), ('logout', 'Logout'), ('password_changed', 'Password changed'), ('two_factor_enabled', 'Two-factor enabled'), ('screenshot_uploaded', 'Screenshot uploaded'), ('ocr_started', 'OCR started'), ('ocr_failed', 'OCR failed'), ('transaction_created', 'Transaction created'), ('transaction_accepted', 'Transaction accepted'), ('transaction_corrected', 'Transaction corrected'), ('transaction_deleted', 'Transaction deleted'), ('duplicate_merged', 'Duplicate merged'), ('category_changed', 'Category changed'), ('export_created', 'Export created'), ('encryption_key_rotated', 'Encryption key rotated')], max_length=64),
        ),
    ]
