# Generated by Django 5.2.17 on 2026-08-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_auditevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Login succeeded'), ('login_failure', 'Login failed'), ('logout', 'Logout'), ('password_changed', 'Password changed'), ('two_factor_enabled', 'Two-factor enabled'), ('screenshot_uploaded', 'Screenshot uploaded'), ('screenshot_deleted', 'Screenshot deleted'), ('ocr_started', 'OCR started'), ('ocr_failed', 'OCR failed'), ('transaction_created', 'Transaction created'), ('transaction_accepted', 'Transaction accepted'), ('transaction_corrected', 'Transaction corrected'), ('transaction_deleted', 'Transaction deleted'), ('duplicate_merged', 'Duplicate merged'), ('category_changed', 'Category changed'), ('payment_instrument_changed', 'Payment instrument changed'), ('merchant_alias_created', 'Merchant alias created'), ('category_rule_created', 'Category rule created'), ('category_rule_enabled', 'Category rule enabled'), ('category_rule_disabled', 'Category rule disabled'), ('category_rule_applied', 'Category rule applied'), ('export_created', 'Export created'), ('encryption_key_rotated', 'Encryption key rotated')], max_length=64),
        ),
    ]
