# Generated by Django 5.2.17 on 2026-08-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_auditevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Login succeeded'), ('login_failure', 'Login failed'), ('logout', 'Logout'), ('password_changed', 'Password changed'), ('two_factor_enabled', 'Two-factor enabled'), ('screenshot_uploaded', 'Screenshot uploaded'), ('screenshot_deleted', 'Screenshot deleted'), ('ocr_started', 'OCR started'), ('ocr_failed', 'OCR failed'), ('transaction_created', 'Transaction created'), ('transaction_accepted', 'Transaction accepted'), ('transaction_corrected', 'Transaction corrected'), ('transaction_voided', 'Transaction voided'), ('opening_balance_posted', 'Opening balance posted'), ('opening_balance_adjusted', 'Opening balance adjusted'), ('transaction_deleted', 'Transaction deleted'), ('observations_imported', 'Observations imported'), ('observation_corrected', 'Observation corrected'), ('observation_accepted', 'Observation accepted'), ('observation_rejected', 'Observation rejected'), ('observation_merged', 'Observation merged'), ('document_reprocess_requested', 'Reprocessing requested'), ('document_override_set', 'Document override set'), ('document_override_cleared', 'Document override cleared'), ('reconciliation_match_created', 'Match proposed'), ('reconciliation_match_confirmed', 'Match confirmed'), ('reconciliation_match_rejected', 'Match rejected'), ('duplicate_merged', 'Duplicate merged'), ('internal_transfer_confirmed', 'Internal transfer confirmed'), ('refund_matched', 'Refund matched to a purchase'), ('category_changed', 'Category changed'), ('payment_instrument_changed', 'Payment instrument changed'), ('merchant_alias_created', 'Merchant alias created'), ('category_rule_created', 'Category rule created'), ('category_rule_enabled', 'Category rule enabled'), ('category_rule_disabled', 'Category rule disabled'), ('category_rule_applied', 'Category rule applied'), ('export_created', 'Export created'), ('export_downloaded', 'Export downloaded'), ('encryption_key_rotated', 'Encryption key rotated'), ('encryption_key_provisioned', 'Encryption key provisioned'), ('encryption_key_accessed', 'Encryption key accessed'), ('worker_key_accessed', "Worker opened the owner's key")], max_length=64),
        ),
    ]
