# Generated by Django 5.2.17 on 2026-08-19 12:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_seal_plaintext_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RotationCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_version', models.PositiveIntegerField()),
                ('model_label', models.CharField(max_length=128)),
                ('last_record_id', models.CharField(blank=True, max_length=64)),
                ('rows_rotated', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotation_checkpoints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user', 'key_version', 'model_label'),
                'indexes': [models.Index(fields=['user', 'key_version'], name='rotation_checkpoint_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'key_version', 'model_label'), name='rotation_checkpoint_unique')],
            },
        ),
    ]
