# Generated by Django 5.2.17 on 2026-08-19 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_auditevent_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rotationcheckpoint',
            options={'ordering': ('user', 'key_kind', 'key_version', 'model_label')},
        ),
        migrations.RemoveConstraint(
            model_name='rotationcheckpoint',
            name='rotation_checkpoint_unique',
        ),
        migrations.AddField(
            model_name='rotationcheckpoint',
            name='key_kind',
            field=models.CharField(default='data', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='rotationcheckpoint',
            constraint=models.UniqueConstraint(fields=('user', 'key_kind', 'key_version', 'model_label'), name='rotation_checkpoint_unique'),
        ),
    ]
