# Generated by Django 5.2.17 on 2026-08-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_rotationcheckpoint_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerHeartbeat',
            fields=[
                ('worker_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('last_seen_at', models.DateTimeField()),
                ('last_job_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['-last_seen_at'], name='worker_heartbeat_seen_idx')],
            },
        ),
    ]
