# Generated by Django 5.2.17 on 2026-08-07 06:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorization', '0002_merchantalias_categoryrule'),
        ('financial_accounts', '0001_initial'),
        ('instruments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('income', 'Income'), ('bank_transfer', 'Bank transfer'), ('internal_transfer', 'Internal transfer'), ('credit_card_payment', 'Credit-card payment'), ('cash_withdrawal', 'Cash withdrawal'), ('refund', 'Refund'), ('fee', 'Fee'), ('interest', 'Interest'), ('loan_payment', 'Loan payment'), ('adjustment', 'Adjustment'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('occurred_at', models.DateField()),
                ('posted_at', models.DateField(blank=True, null=True)),
                ('merchant_encrypted', models.TextField(blank=True)),
                ('merchant_blind_index', models.CharField(blank=True, max_length=128)),
                ('counterparty_encrypted', models.TextField(blank=True)),
                ('counterparty_blind_index', models.CharField(blank=True, max_length=128)),
                ('amount_encrypted', models.TextField()),
                ('currency', models.CharField(default='KRW', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('voided', 'Voided')], default='draft', max_length=16)),
                ('notes_encrypted', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='canonical_transactions', to='categorization.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_canonical_transactions', to=settings.AUTH_USER_MODEL)),
                ('financial_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canonical_transactions', to='financial_accounts.financialaccount')),
                ('payment_instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='canonical_transactions', to='instruments.paymentinstrument')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_canonical_transactions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canonical_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-occurred_at', '-created_at'),
                'indexes': [models.Index(fields=['user', 'occurred_at'], name='transaction_user_date_idx'), models.Index(fields=['user', 'status'], name='transaction_user_status_idx'), models.Index(fields=['user', 'merchant_blind_index'], name='transaction_merchant_idx')],
            },
        ),
    ]
