# Generated by Django 5.2.17 on 2026-08-17 05:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorization', '0003_remove_merchantalias_merchant_alias_user_alias_card_unique_and_more'),
        ('financial_accounts', '0002_financialaccount_financial_account_type_valid'),
        ('instruments', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='canonicaltransaction',
            name='source_idempotency_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddConstraint(
            model_name='canonicaltransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('source_idempotency_key', ''), _negated=True), fields=('user', 'source_idempotency_key'), name='transaction_source_idempotency_unique'),
        ),
    ]
