# Generated by Django 5.2.17 on 2026-08-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_canonicaltransaction_source_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canonicaltransaction',
            name='category_source',
            field=models.CharField(default='uncategorized', max_length=32),
        ),
    ]
