# Generated by Django 5.2.17 on 2026-08-19 11:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorization', '0003_remove_merchantalias_merchant_alias_user_alias_card_unique_and_more'),
        ('financial_accounts', '0003_financialaccount_identifier_blind_index_and_more'),
        ('instruments', '0001_initial'),
        ('transactions', '0004_alter_canonicaltransaction_transaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='canonicaltransaction',
            index=models.Index(fields=['user', 'counterparty_blind_index'], name='transaction_counterparty_idx'),
        ),
    ]
