# Generated by Django 5.2.17 on 2026-08-19 11:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userdatakey'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSearchKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('wrapped_key', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user', 'version'),
                'constraints': [models.UniqueConstraint(fields=('user', 'version'), name='user_search_key_version_unique'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='user_search_key_one_active'), models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='user_search_key_version_positive')],
            },
        ),
    ]
