# Generated by Django 5.2.17 on 2026-08-16 12:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('observations', '0002_importedobservation_amount_uncertain_and_more'),
        ('processing', '0005_sourcedocument_perceptual_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NearDuplicateDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('distance', models.PositiveSmallIntegerField()),
                ('algorithm', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='near_duplicate_links', to='processing.sourcedocument')),
                ('similar_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='near_duplicate_backlinks', to='processing.sourcedocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='near_duplicate_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('distance', '-created_at'),
                'indexes': [models.Index(fields=['user', 'distance'], name='near_duplicate_user_idx')],
                'constraints': [models.UniqueConstraint(fields=('document', 'similar_document'), name='near_duplicate_pair_unique'), models.CheckConstraint(condition=models.Q(('document', models.F('similar_document')), _negated=True), name='near_duplicate_distinct_documents')],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_type', models.CharField(choices=[('duplicate_observation', 'Duplicate observation'), ('debit_card_bank_match', 'Debit-card and bank match'), ('credit_card_payment', 'Credit-card payment'), ('internal_transfer', 'Internal transfer'), ('refund_match', 'Refund match'), ('statement_membership', 'Statement membership')], max_length=32)),
                ('match_score', models.PositiveSmallIntegerField(default=0)),
                ('match_features_json_encrypted', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='proposed', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('left_observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_matches', to='observations.importedobservation')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_reconciliation_matches', to=settings.AUTH_USER_MODEL)),
                ('right_observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_matches', to='observations.importedobservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-match_score', '-created_at'),
                'indexes': [models.Index(fields=['user', 'status', '-match_score'], name='match_user_status_idx'), models.Index(fields=['user', 'match_type'], name='match_user_type_idx')],
                'constraints': [models.UniqueConstraint(fields=('left_observation', 'right_observation', 'match_type'), name='reconciliation_pair_unique'), models.CheckConstraint(condition=models.Q(('left_observation', models.F('right_observation')), _negated=True), name='reconciliation_distinct_observations'), models.CheckConstraint(condition=models.Q(('match_score__lte', 100)), name='reconciliation_score_range')],
            },
        ),
    ]
