# Generated by Django 5.2.17 on 2026-08-16 11:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorization', '0003_remove_merchantalias_merchant_alias_user_alias_card_unique_and_more'),
        ('financial_accounts', '0002_financialaccount_financial_account_type_valid'),
        ('instruments', '0001_initial'),
        ('ocr', '0003_ocrtoken_normalized_text_encrypted'),
        ('processing', '0004_sourcedocument_retention_deadline_and_more'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_index', models.PositiveIntegerField(default=0)),
                ('occurred_at', models.DateField(blank=True, null=True)),
                ('posted_at', models.DateField(blank=True, null=True)),
                ('merchant_raw_encrypted', models.TextField(blank=True)),
                ('merchant_normalized_encrypted', models.TextField(blank=True)),
                ('merchant_blind_index', models.CharField(blank=True, max_length=128)),
                ('counterparty_raw_encrypted', models.TextField(blank=True)),
                ('amount_encrypted', models.TextField(blank=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('direction', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('balance_after_encrypted', models.TextField(blank=True)),
                ('approval_code_encrypted', models.TextField(blank=True)),
                ('installment_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('transaction_type_guess', models.CharField(choices=[('purchase', 'Purchase'), ('income', 'Income'), ('bank_transfer', 'Bank transfer'), ('internal_transfer', 'Internal transfer'), ('credit_card_payment', 'Credit-card payment'), ('cash_withdrawal', 'Cash withdrawal'), ('refund', 'Refund'), ('fee', 'Fee'), ('interest', 'Interest'), ('loan_payment', 'Loan payment'), ('adjustment', 'Adjustment'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('ocr_confidence', models.FloatField(default=0.0)),
                ('parser_confidence', models.FloatField(default=0.0)),
                ('overall_confidence', models.FloatField(default=0.0)),
                ('source_region_json_encrypted', models.TextField(blank=True)),
                ('parser_name', models.CharField(blank=True, max_length=64)),
                ('parser_version', models.CharField(blank=True, max_length=32)),
                ('parser_output_version', models.PositiveSmallIntegerField(default=1)),
                ('review_flags', models.JSONField(blank=True, default=list)),
                ('requires_review', models.BooleanField(default=True)),
                ('review_status', models.CharField(choices=[('unreviewed', 'Unreviewed'), ('accepted', 'Accepted'), ('corrected', 'Corrected'), ('rejected', 'Rejected'), ('merged', 'Merged')], default='unreviewed', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('corrected_fields', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canonical_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='transactions.canonicaltransaction')),
                ('category_guess', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observation_guesses', to='categorization.category')),
                ('financial_account_guess', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observation_guesses', to='financial_accounts.financialaccount')),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='observations.importedobservation')),
                ('ocr_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_observations', to='ocr.ocrrun')),
                ('payment_instrument_guess', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observation_guesses', to='instruments.paymentinstrument')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_observations', to=settings.AUTH_USER_MODEL)),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_observations', to='processing.sourcedocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_observations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('source_document_id', 'row_index', 'created_at'),
                'indexes': [models.Index(fields=['user', 'review_status'], name='observation_user_status_idx'), models.Index(fields=['user', 'occurred_at'], name='observation_user_date_idx'), models.Index(fields=['user', 'merchant_blind_index'], name='observation_merchant_idx'), models.Index(fields=['source_document', 'row_index'], name='observation_document_row_idx')],
                'constraints': [models.UniqueConstraint(fields=('ocr_run', 'parser_name', 'parser_version', 'row_index'), name='observation_unique_per_run_row'), models.CheckConstraint(condition=models.Q(('overall_confidence__gte', 0.0), ('overall_confidence__lte', 1.0)), name='observation_confidence_range')],
            },
        ),
    ]
