# Generated by Django 5.2.17 on 2026-08-16 12:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorization', '0003_remove_merchantalias_merchant_alias_user_alias_card_unique_and_more'),
        ('financial_accounts', '0002_financialaccount_financial_account_type_valid'),
        ('instruments', '0001_initial'),
        ('observations', '0001_initial'),
        ('ocr', '0003_ocrtoken_normalized_text_encrypted'),
        ('processing', '0004_sourcedocument_retention_deadline_and_more'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importedobservation',
            name='amount_uncertain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='importedobservation',
            name='balance_mismatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='importedobservation',
            name='has_missing_fields',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='importedobservation',
            name='is_settlement_candidate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='importedobservation',
            name='risk_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='importedobservation',
            index=models.Index(fields=['user', 'review_status', '-risk_score'], name='observation_queue_idx'),
        ),
    ]
