# Generated by Django 5.2.17 on 2026-08-17 05:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorization', '0003_remove_merchantalias_merchant_alias_user_alias_card_unique_and_more'),
        ('financial_accounts', '0002_financialaccount_financial_account_type_valid'),
        ('instruments', '0001_initial'),
        ('observations', '0002_importedobservation_amount_uncertain_and_more'),
        ('ocr', '0003_ocrtoken_normalized_text_encrypted'),
        ('processing', '0005_sourcedocument_perceptual_hash'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='importedobservation',
            constraint=models.CheckConstraint(condition=models.Q(('merged_into__isnull', True), ('canonical_transaction__isnull', True), _connector='OR'), name='observation_merged_rows_have_no_transaction'),
        ),
        migrations.AddConstraint(
            model_name='importedobservation',
            constraint=models.CheckConstraint(condition=models.Q(('merged_into__isnull', True), ('review_status', 'merged'), _connector='OR'), name='observation_merged_rows_say_so'),
        ),
    ]
