# Generated by Django 5.2.17 on 2026-08-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0003_importedobservation_observation_merged_rows_have_no_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedobservation',
            name='transaction_type_guess',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('income', 'Income'), ('bank_transfer', 'Bank transfer'), ('internal_transfer', 'Internal transfer'), ('credit_card_payment', 'Credit-card payment'), ('cash_withdrawal', 'Cash withdrawal'), ('refund', 'Refund'), ('fee', 'Fee'), ('interest', 'Interest'), ('loan_payment', 'Loan payment'), ('adjustment', 'Adjustment'), ('opening_balance', 'Opening balance'), ('unknown', 'Unknown')], default='unknown', max_length=32),
        ),
    ]
