# Generated by Django 5.2.17 on 2026-08-19 11:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorization', '0003_remove_merchantalias_merchant_alias_user_alias_card_unique_and_more'),
        ('financial_accounts', '0003_financialaccount_identifier_blind_index_and_more'),
        ('instruments', '0001_initial'),
        ('observations', '0004_alter_importedobservation_transaction_type_guess'),
        ('ocr', '0004_alter_ocrrun_engine'),
        ('processing', '0006_sourcedocument_institution_override_and_more'),
        ('transactions', '0005_canonicaltransaction_transaction_counterparty_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importedobservation',
            name='approval_code_blind_index',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddIndex(
            model_name='importedobservation',
            index=models.Index(fields=['user', 'approval_code_blind_index'], name='observation_approval_idx'),
        ),
    ]
