# Generated by Django 5.2.17 on 2026-08-23 15:41

import hashlib

from django.conf import settings
from django.db import migrations, models


def populate_import_keys(apps, schema_editor):
    ImportedObservation = apps.get_model("observations", "ImportedObservation")
    for observation in ImportedObservation.objects.all().iterator():
        identity = "\x1f".join(
            str(value or "")
            for value in (
                observation.source_document_id,
                observation.ocr_run_id,
                observation.parser_name,
                observation.parser_version,
                observation.parser_output_version,
                observation.row_index,
            )
        )
        observation.import_key = hashlib.sha256(identity.encode("utf-8")).hexdigest()
        observation.save(update_fields=["import_key"])


def clear_import_keys(apps, schema_editor):
    ImportedObservation = apps.get_model("observations", "ImportedObservation")
    ImportedObservation.objects.update(import_key="")


class Migration(migrations.Migration):
    dependencies = [
        (
            "categorization",
            "0003_remove_merchantalias_merchant_alias_user_alias_card_unique_and_more",
        ),
        ("financial_accounts", "0003_financialaccount_identifier_blind_index_and_more"),
        ("instruments", "0001_initial"),
        ("observations", "0005_importedobservation_approval_code_blind_index_and_more"),
        ("ocr", "0004_alter_ocrrun_engine"),
        ("processing", "0006_sourcedocument_institution_override_and_more"),
        ("transactions", "0005_canonicaltransaction_transaction_counterparty_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="importedobservation",
            name="import_key",
            field=models.CharField(default="", editable=False, max_length=64),
            preserve_default=False,
        ),
        migrations.RunPython(
            populate_import_keys,
            clear_import_keys,
        ),
        migrations.AddConstraint(
            model_name="importedobservation",
            constraint=models.UniqueConstraint(
                fields=("import_key",), name="observation_import_key_unique"
            ),
        ),
    ]
