# Generated by Django 5.2.17 on 2026-08-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0006_importedobservation_import_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedobservation',
            name='import_key',
            field=models.CharField(blank=True, default='', editable=False, max_length=64),
        ),
    ]
