# Generated by Django 5.2.17 on 2026-08-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QualityMetricDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("day", models.DateField()),
                ("institution", models.CharField(max_length=64)),
                ("source_type", models.CharField(max_length=40)),
                ("observations_count", models.PositiveIntegerField(default=0)),
                ("corrected_count", models.PositiveIntegerField(default=0)),
                ("disagreement_count", models.PositiveIntegerField(default=0)),
                ("duplicate_candidates_count", models.PositiveIntegerField(default=0)),
                ("duplicate_confirmed_count", models.PositiveIntegerField(default=0)),
                ("ocr_issue_count", models.PositiveIntegerField(default=0)),
                ("parser_issue_count", models.PositiveIntegerField(default=0)),
                ("correction_rate", models.DecimalField(decimal_places=5, default=0, max_digits=6)),
                (
                    "disagreement_rate",
                    models.DecimalField(decimal_places=5, default=0, max_digits=6),
                ),
                ("duplicate_rate", models.DecimalField(decimal_places=5, default=0, max_digits=6)),
                ("ocr_issue_rate", models.DecimalField(decimal_places=5, default=0, max_digits=6)),
                (
                    "parser_issue_rate",
                    models.DecimalField(decimal_places=5, default=0, max_digits=6),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["day", "institution"], name="quality_metric_daily_day_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("day", "institution", "source_type"),
                        name="quality_metric_daily_dimension_unique",
                    ),
                ],
            },
        ),
    ]
