# Generated by Django 5.2.17 on 2026-08-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_qualitymetricdaily'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='qualitymetricdaily',
            name='quality_metric_daily_dimension_unique',
        ),
        migrations.AddField(
            model_name='qualitymetricdaily',
            name='engine',
            field=models.CharField(default='unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='qualitymetricdaily',
            name='mean_confidence',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=6),
        ),
        migrations.AddConstraint(
            model_name='qualitymetricdaily',
            constraint=models.UniqueConstraint(fields=('day', 'institution', 'source_type', 'engine'), name='quality_metric_daily_dimension_unique'),
        ),
    ]
