# Generated by Django 5.2.17 on 2026-08-07 06:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_encrypted', models.TextField()),
                ('name_blind_index', models.CharField(max_length=128)),
                ('category_type', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('transfer', 'Transfer'), ('other', 'Other')], max_length=16)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='categorization.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name_blind_index', 'created_at'),
                'indexes': [models.Index(fields=['user', 'parent'], name='category_user_parent_idx'), models.Index(fields=['user', 'category_type'], name='category_user_type_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'parent', 'name_blind_index'), name='category_user_parent_name_blind_unique')],
            },
        ),
    ]
