# Generated by Django 5.2.17 on 2026-08-14 06:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorization', '0002_merchantalias_categoryrule'),
        ('instruments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='merchantalias',
            name='merchant_alias_user_alias_card_unique',
        ),
        migrations.AddField(
            model_name='categoryrule',
            name='disabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='merchantalias',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_instrument__isnull', True)), fields=('user', 'alias_blind_index'), name='merchant_alias_user_alias_generic_unique'),
        ),
        migrations.AddConstraint(
            model_name='merchantalias',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_instrument__isnull', False)), fields=('user', 'alias_blind_index', 'payment_instrument'), name='merchant_alias_user_alias_card_unique'),
        ),
    ]
