# Generated by Django 5.2.17 on 2026-08-09 12:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_sha256', models.CharField(db_index=True, max_length=64)),
                ('original_filename_encrypted', models.TextField()),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveBigIntegerField()),
                ('image_width', models.PositiveIntegerField(blank=True, null=True)),
                ('image_height', models.PositiveIntegerField(blank=True, null=True)),
                ('source_institution_guess_encrypted', models.TextField(blank=True)),
                ('source_type', models.CharField(choices=[('bank_transaction_list', 'Bank transaction list'), ('bank_transaction_detail', 'Bank transaction detail'), ('bank_transfer_confirmation', 'Bank transfer confirmation'), ('card_transaction_list', 'Card transaction list'), ('card_transaction_detail', 'Card transaction detail'), ('credit_card_statement', 'Credit-card statement'), ('credit_card_payment', 'Credit-card payment'), ('unknown', 'Unknown')], default='unknown', max_length=40)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('validating', 'Validating'), ('queued', 'Queued'), ('preprocessing', 'Preprocessing'), ('ocr_running', 'OCR running'), ('parsing', 'Parsing'), ('ready_for_review', 'Ready for review'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('deleted', 'Deleted')], default='pending', max_length=24)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message_encrypted', models.TextField(blank=True)),
                ('temporary_path', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_attempt_count', models.PositiveIntegerField(default=0)),
                ('next_processing_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('original_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-uploaded_at',),
                'indexes': [models.Index(fields=['user', 'processing_status'], name='source_doc_user_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'file_sha256'), name='source_document_user_sha256_unique')],
            },
        ),
    ]
