# Generated by Django 5.2.17 on 2026-08-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_sourcedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedocument',
            name='cleanup_error_code',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
