# Generated by Django 5.2.17 on 2026-08-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0003_sourcedocument_cleanup_error_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedocument',
            name='retention_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourcedocument',
            name='retention_policy',
            field=models.CharField(choices=[('immediate', 'Delete after processing'), ('one_day', 'Retain for one day'), ('seven_days', 'Retain for seven days'), ('thirty_days', 'Retain for thirty days')], default='immediate', max_length=16),
        ),
    ]
