# Generated by Django 5.2.17 on 2026-08-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0004_sourcedocument_retention_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedocument',
            name='perceptual_hash',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
    ]
