# Generated by Django 5.2.17 on 2026-08-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0005_sourcedocument_perceptual_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedocument',
            name='institution_override',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='sourcedocument',
            name='source_type_override',
            field=models.CharField(blank=True, choices=[('bank_transaction_list', 'Bank transaction list'), ('bank_transaction_detail', 'Bank transaction detail'), ('bank_transfer_confirmation', 'Bank transfer confirmation'), ('card_transaction_list', 'Card transaction list'), ('card_transaction_detail', 'Card transaction detail'), ('credit_card_statement', 'Credit-card statement'), ('credit_card_payment', 'Credit-card payment'), ('unknown', 'Unknown')], max_length=40),
        ),
    ]
