# Generated by Django 5.2.17 on 2026-08-25 07:32

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count
from django.utils import timezone


def reject_duplicate_active_jobs(apps, schema_editor):  # type: ignore[no-untyped-def]
    ProcessingJob = apps.get_model("processing", "ProcessingJob")
    duplicates = (
        ProcessingJob.objects.filter(
            task_name="process_document",
            status__in=("queued", "running"),
        )
        .values("document_id")
        .annotate(active_count=Count("id"))
        .filter(active_count__gt=1)
    )
    now = timezone.now()
    for duplicate in duplicates.iterator():
        active = ProcessingJob.objects.filter(
            document_id=duplicate["document_id"],
            task_name="process_document",
            status__in=("queued", "running"),
        )
        running = active.filter(status="running").order_by("created_at").first()
        retained = running or active.order_by("created_at").first()
        active.exclude(pk=retained.pk).update(
            status="failed",
            locked_at=None,
            completed_at=now,
            last_error_code="DUPLICATE_DOCUMENT_JOB",
            last_error_message="A duplicate document-processing job was rejected.",
            updated_at=now,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("processing", "0006_sourcedocument_institution_override_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(reject_duplicate_active_jobs, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="processingjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ("queued", "running")), ("task_name", "process_document")
                ),
                fields=("document_id",),
                name="processing_one_active_job_per_document",
            ),
        ),
    ]
